// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

listener http:Listener ep0 = new (443, config = {host: "api.openai.com"});

service /v1 on ep0 {
    # Delete a file.
    #
    # + fileId - The ID of the file to use for this request
    # + return - OK 
    resource function delete files/[string fileId]() returns DeleteFileResponse {
    }

    # Delete a fine-tuned model. You must have the Owner role in your organization.
    #
    # + model - The model to delete
    # + return - OK 
    resource function delete models/[string model]() returns DeleteModelResponse {
    }

    # Returns a list of files that belong to the user's organization.
    #
    # + return - OK 
    resource function get files() returns ListFilesResponse {
    }

    # Returns information about a specific file.
    #
    # + fileId - The ID of the file to use for this request
    # + return - OK 
    resource function get files/[string fileId]() returns OpenAIFile {
    }

    # Returns the contents of the specified file
    #
    # + fileId - The ID of the file to use for this request
    # + return - OK 
    resource function get files/[string fileId]/content() returns string {
    }

    resource function get fine\-tunes() returns ListFineTunesResponse {
    }

    resource function get fine\-tunes/[string fineTuneId]() returns FineTune {
    }

    resource function get fine\-tunes/[string fineTuneId]/events(boolean 'stream = false) returns ListFineTuneEventsResponse {
    }

    # Lists the currently available models, and provides basic information about each one such as the owner and availability.
    #
    # + return - OK 
    resource function get models() returns ListModelsResponse {
    }

    # Retrieves a model instance, providing basic information about the model such as the owner and permissioning.
    #
    # + model - The ID of the model to use for this request
    # + return - OK 
    resource function get models/[string model]() returns Model {
    }

    # Transcribes audio into the input language.
    #
    # + return - OK 
    resource function post audio/transcriptions(http:Request request) returns CreateTranscriptionResponseOk {
    }

    # Translates audio into English.
    #
    # + return - OK 
    resource function post audio/translations(http:Request request) returns CreateTranslationResponseOk {
    }

    # Creates a model response for the given chat conversation.
    #
    # + return - OK 
    resource function post chat/completions(@http:Payload CreateChatCompletionRequest payload) returns CreateChatCompletionResponseOk {
    }

    # Creates a completion for the provided prompt and parameters.
    #
    # + return - OK 
    resource function post completions(@http:Payload CreateCompletionRequest payload) returns CreateCompletionResponseOk {
    }

    # Creates a new edit for the provided input, instruction, and parameters.
    #
    # + return - OK 
    resource function post edits(@http:Payload CreateEditRequest payload) returns CreateEditResponseOk {
    }

    # Creates an embedding vector representing the input text.
    #
    # + return - OK 
    resource function post embeddings(@http:Payload CreateEmbeddingRequest payload) returns CreateEmbeddingResponseOk {
    }

    # Upload a file that contains document(s) to be used across various endpoints/features. Currently, the size of all the files uploaded by one organization can be up to 1 GB. Please contact us if you need to increase the storage limit.
    #
    # + return - OK 
    resource function post files(http:Request request) returns OpenAIFileOk {
    }

    resource function post fine\-tunes(@http:Payload CreateFineTuneRequest payload) returns FineTuneOk {
    }

    resource function post fine\-tunes/[string fineTuneId]/cancel() returns FineTuneOk {
    }

    # Creates an edited or extended image given an original image and a prompt.
    #
    # + return - OK 
    resource function post images/edits(http:Request request) returns ImagesResponseOk {
    }

    # Creates an image given a prompt.
    #
    # + return - OK 
    resource function post images/generations(@http:Payload CreateImageRequest payload) returns ImagesResponseOk {
    }

    # Creates a variation of a given image.
    #
    # + return - OK 
    resource function post images/variations(http:Request request) returns ImagesResponseOk {
    }

    # Classifies if text violates OpenAI's Content Policy
    #
    # + return - OK 
    resource function post moderations(@http:Payload CreateModerationRequest payload) returns CreateModerationResponseOk {
    }
}
