// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/constraint;
import ballerina/data.jsondata;
import ballerina/http;

public type CreateTranscriptionResponse record {
    string text;
};

public type CreateChatCompletionResponseChoices record {
    @jsondata:Name {value: "finish_reason"}
    "stop"|"length"|"function_call" finishReason?;
    int index?;
    ChatCompletionResponseMessage message?;
};

public type CreateEditRequest record {
    # An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.
    # 
    # We generally recommend altering this or `temperature` but not both
    @jsondata:Name {value: "top_p"}
    decimal? topP = 1;
    # The input text to use as a starting point for the edit
    string? input = "";
    # The instruction that tells the model how to edit the prompt
    string instruction;
    # What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.
    # 
    # We generally recommend altering this or `top_p` but not both
    decimal? temperature = 1;
    # ID of the model to use. You can use the `text-davinci-edit-001` or `code-davinci-edit-001` model with this endpoint
    string|"text-davinci-edit-001"|"code-davinci-edit-001" model;
    # How many edits to generate for the input and instruction
    int? n = 1;
};

public type CreateImageRequest record {
    # The format in which the generated images are returned. Must be one of `url` or `b64_json`
    @jsondata:Name {value: "response_format"}
    "url"|"b64_json"? responseFormat = "url";
    # The size of the generated images. Must be one of `256x256`, `512x512`, or `1024x1024`
    "256x256"|"512x512"|"1024x1024"? size = "1024x1024";
    # A text description of the desired image(s). The maximum length is 1000 characters
    string prompt;
    # A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids)
    string user?;
    # The number of images to generate. Must be between 1 and 10
    int? n = 1;
};

public type ChatCompletionRequestMessage record {
    # The role of the messages author. One of `system`, `user`, `assistant`, or `function`
    "system"|"user"|"assistant"|"function" role;
    @jsondata:Name {value: "function_call"}
    ChatCompletionRequestMessageFunctionCall functionCall?;
    # The name of the author of this message. `name` is required if role is `function`, and it should be the name of the function whose response is in the `content`. May contain a-z, A-Z, 0-9, and underscores, with a maximum length of 64 characters
    string name?;
    # The contents of the message. `content` is required for all messages except assistant messages with function calls
    string content?;
};

public type CreateTranscriptionRequest record {|
    # The audio file object (not file name) to transcribe, in one of these formats: mp3, mp4, mpeg, mpga, m4a, wav, or webm
    record {byte[] fileContent; string fileName;} file;
    # The format of the transcript output, in one of these options: json, text, srt, verbose_json, or vtt
    @jsondata:Name {value: "response_format"}
    string responseFormat = "json";
    # The sampling temperature, between 0 and 1. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. If set to 0, the model will use [log probability](https://en.wikipedia.org/wiki/Log_probability) to automatically increase the temperature until certain thresholds are hit
    decimal temperature = 0;
    # ID of the model to use. Only `whisper-1` is currently available
    string|"whisper-1" model;
    # The language of the input audio. Supplying the input language in [ISO-639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) format will improve accuracy and latency
    string language?;
    # An optional text to guide the model's style or continue a previous audio segment. The [prompt](/docs/guides/speech-to-text/prompting) should match the audio language
    string prompt?;
|};

public type InputItemsArray int[];

public type ImagesResponseOk record {|
    *http:Ok;
    ImagesResponse body;
|};

public type CreateTranslationRequest record {|
    # The audio file object (not file name) translate, in one of these formats: mp3, mp4, mpeg, mpga, m4a, wav, or webm
    record {byte[] fileContent; string fileName;} file;
    # The format of the transcript output, in one of these options: json, text, srt, verbose_json, or vtt
    @jsondata:Name {value: "response_format"}
    string responseFormat = "json";
    # The sampling temperature, between 0 and 1. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. If set to 0, the model will use [log probability](https://en.wikipedia.org/wiki/Log_probability) to automatically increase the temperature until certain thresholds are hit
    decimal temperature = 0;
    # ID of the model to use. Only `whisper-1` is currently available
    string|"whisper-1" model;
    # An optional text to guide the model's style or continue a previous audio segment. The [prompt](/docs/guides/speech-to-text/prompting) should be in English
    string prompt?;
|};

public type ListFineTunesResponse record {
    FineTune[] data;
    string 'object;
};

public type CreateModerationResponse record {
    string model;
    string id;
    CreateModerationResponseResults[] results;
};

public type CreateEmbeddingResponse record {
    CreateEmbeddingResponseData[] data;
    CreateEmbeddingResponseUsage usage;
    string model;
    string 'object;
};

public type FineTune record {
    string id;
    string 'object;
    int created_at;
    int updated_at;
    string model;
    string? fine_tuned_model;
    string organization_id;
    string status;
    record {} hyperparams;
    OpenAIFile[] training_files;
    OpenAIFile[] validation_files;
    OpenAIFile[] result_files;
    FineTuneEvent[] events?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

public type ImagesResponseData record {
    @jsondata:Name {value: "b64_json"}
    string b64Json?;
    string url?;
};

public type ListFineTuneEventsResponse record {
    FineTuneEvent[] data;
    string 'object;
};

public type CreateEmbeddingResponseOk record {|
    *http:Ok;
    CreateEmbeddingResponse body;
|};

public type CreateEmbeddingRequest record {|
    # Input text to embed, encoded as a string or array of tokens. To embed multiple inputs in a single request, pass an array of strings or array of token arrays. Each input must not exceed the max input tokens for the model (8191 tokens for `text-embedding-ada-002`). [Example Python code](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb) for counting tokens
    string|string[]|int[]|InputItemsArray[] input;
    # ID of the model to use. You can use the [List models](/docs/api-reference/models/list) API to see all of your available models, or see our [Model overview](/docs/models/overview) for descriptions of them
    string|"text-embedding-ada-002" model;
    # A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids)
    string user?;
|};

public type OpenAIFileOk record {|
    *http:Ok;
    OpenAIFile body;
|};

public type ChatCompletionFunctions record {
    # The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64
    string name;
    # The description of what the function does
    string description?;
    # The parameters the functions accepts, described as a JSON Schema object. See the [guide](/docs/guides/gpt/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format
    ChatCompletionFunctionParameters parameters?;
};

public type CreateCompletionResponseOk record {|
    *http:Ok;
    CreateCompletionResponse body;
|};

public type CreateTranslationResponseOk record {|
    *http:Ok;
    CreateTranslationResponse body;
|};

public type CreateModerationRequest record {
    # The input text to classify
    string|string[] input;
    # Two content moderations models are available: `text-moderation-stable` and `text-moderation-latest`.
    # 
    # The default is `text-moderation-latest` which will be automatically upgraded over time. This ensures you are always using our most accurate model. If you use `text-moderation-stable`, we will provide advanced notice before updating the model. Accuracy of `text-moderation-stable` may be slightly lower than for `text-moderation-latest`
    string|"text-moderation-latest"|"text-moderation-stable" model = "text-moderation-latest";
};

public type CreateEmbeddingResponseUsage record {
    @jsondata:Name {value: "prompt_tokens"}
    int promptTokens;
    @jsondata:Name {value: "total_tokens"}
    int totalTokens;
};

public type CreateCompletionResponseLogprobs record {
    @jsondata:Name {value: "top_logprobs"}
    record {}[] topLogprobs?;
    @jsondata:Name {value: "token_logprobs"}
    decimal[] tokenLogprobs?;
    string[] tokens?;
    @jsondata:Name {value: "text_offset"}
    int[] textOffset?;
};

public type DeleteFileResponse record {
    boolean deleted;
    string id;
    string 'object;
};

public type CreateEditResponse record {
    int created;
    CreateCompletionResponseUsage usage;
    CreateEditResponseChoices[] choices;
    string 'object;
};

public type CreateEditResponseOk record {|
    *http:Ok;
    CreateEditResponse body;
|};

public type OpenAIFile record {
    string id;
    string 'object;
    int bytes;
    int created_at;
    string filename;
    string purpose;
    string status?;
    record {}? status_details?;
};

public type CreateModerationResponseResults record {
    @jsondata:Name {value: "category_scores"}
    CreateModerationResponseCategoryScores categoryScores;
    boolean flagged;
    CreateModerationResponseCategories categories;
};

public type CreateChatCompletionResponseOk record {|
    *http:Ok;
    CreateChatCompletionResponse body;
|};

public type CreateCompletionResponseUsage record {
    @jsondata:Name {value: "completion_tokens"}
    int completionTokens;
    @jsondata:Name {value: "prompt_tokens"}
    int promptTokens;
    @jsondata:Name {value: "total_tokens"}
    int totalTokens;
};

# Represents the Queries record for the operation: listFineTuneEvents
public type ListFineTuneEventsQueries record {
    # Whether to stream events for the fine-tune job. If set to true,
    # events will be sent as data-only
    # [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format)
    # as they become available. The stream will terminate with a
    # `data: [DONE]` message when the job is finished (succeeded, cancelled,
    # or failed).
    # 
    # If set to false, only events generated so far will be returned
    boolean 'stream = false;
};

public type CreateModerationResponseCategoryScores record {
    @jsondata:Name {value: "hate/threatening"}
    decimal hateThreatening;
    @jsondata:Name {value: "sexual/minors"}
    decimal sexualMinors;
    decimal hate;
    @jsondata:Name {value: "self-harm"}
    decimal selfHarm;
    decimal sexual;
    @jsondata:Name {value: "violence/graphic"}
    decimal violenceGraphic;
    decimal violence;
};

public type CreateEditResponseChoices record {
    @jsondata:Name {value: "finish_reason"}
    "stop"|"length" finishReason?;
    int index?;
    string text?;
    CreateCompletionResponseLogprobs? logprobs?;
};

public type CreateChatCompletionRequest record {
    # Modify the likelihood of specified tokens appearing in the completion.
    # 
    # Accepts a json object that maps tokens (specified by their token ID in the tokenizer) to an associated bias value from -100 to 100. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token
    @jsondata:Name {value: "logit_bias"}
    record {}? logitBias?;
    # A list of functions the model may generate JSON inputs for
    @constraint:Array {minLength: 1}
    ChatCompletionFunctions[] functions?;
    # Controls how the model responds to function calls. "none" means the model does not call a function, and responds to the end-user. "auto" means the model can pick between an end-user or calling a function.  Specifying a particular function via `{"name":\ "my_function"}` forces the model to call that function. "none" is the default when no functions are present. "auto" is the default if functions are present
    @jsondata:Name {value: "function_call"}
    "none"|"auto"|record {string name;} functionCall?;
    # The maximum number of [tokens](/tokenizer) to generate in the chat completion.
    # 
    # The total length of input tokens and generated tokens is limited by the model's context length. [Example Python code](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb) for counting tokens
    @jsondata:Name {value: "max_tokens"}
    int maxTokens?;
    # Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.
    # 
    # [See more information about frequency and presence penalties.](/docs/api-reference/parameter-details)
    @jsondata:Name {value: "presence_penalty"}
    decimal? presencePenalty = 0;
    # How many chat completion choices to generate for each input message
    int? n = 1;
    # An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.
    # 
    # We generally recommend altering this or `temperature` but not both
    @jsondata:Name {value: "top_p"}
    decimal? topP = 1;
    # Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim.
    # 
    # [See more information about frequency and presence penalties.](/docs/api-reference/parameter-details)
    @jsondata:Name {value: "frequency_penalty"}
    decimal? frequencyPenalty = 0;
    # Up to 4 sequences where the API will stop generating further tokens
    string|string[]? stop = ();
    # If set, partial message deltas will be sent, like in ChatGPT. Tokens will be sent as data-only [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format) as they become available, with the stream terminated by a `data: [DONE]` message. [Example Python code](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_stream_completions.ipynb)
    boolean? 'stream = false;
    # What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.
    # 
    # We generally recommend altering this or `top_p` but not both
    decimal? temperature = 1;
    # A list of messages comprising the conversation so far. [Example Python code](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_format_inputs_to_ChatGPT_models.ipynb)
    @constraint:Array {minLength: 1}
    ChatCompletionRequestMessage[] messages;
    # ID of the model to use. See the [model endpoint compatibility](/docs/models/model-endpoint-compatibility) table for details on which models work with the Chat API
    string|"gpt-4"|"gpt-4-0613"|"gpt-4-32k"|"gpt-4-32k-0613"|"gpt-3.5-turbo"|"gpt-3.5-turbo-16k"|"gpt-3.5-turbo-0613"|"gpt-3.5-turbo-16k-0613" model;
    # A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids)
    string user?;
};

public type CreateModerationResponseCategories record {
    @jsondata:Name {value: "hate/threatening"}
    boolean hateThreatening;
    @jsondata:Name {value: "sexual/minors"}
    boolean sexualMinors;
    boolean hate;
    @jsondata:Name {value: "self-harm"}
    boolean selfHarm;
    boolean sexual;
    @jsondata:Name {value: "violence/graphic"}
    boolean violenceGraphic;
    boolean violence;
};

public type FineTuneOk record {|
    *http:Ok;
    FineTune body;
|};

public type CreateCompletionResponseChoices record {
    @jsondata:Name {value: "finish_reason"}
    "stop"|"length" finishReason;
    int index;
    string text;
    CreateCompletionResponseLogprobs? logprobs;
};

public type ImagesResponse record {
    int created;
    ImagesResponseData[] data;
};

public type DeleteModelResponse record {
    boolean deleted;
    string id;
    string 'object;
};

public type CreateTranscriptionResponseOk record {|
    *http:Ok;
    CreateTranscriptionResponse body;
|};

public type CreateTranslationResponse record {
    string text;
};

public type FineTuneEvent record {
    string 'object;
    int created_at;
    string level;
    string message;
};

# The name and arguments of a function that should be called, as generated by the model
public type ChatCompletionRequestMessageFunctionCall record {
    # The name of the function to call
    string name?;
    # The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function
    string arguments?;
};

public type CreateCompletionRequest record {
    # Modify the likelihood of specified tokens appearing in the completion.
    # 
    # Accepts a json object that maps tokens (specified by their token ID in the GPT tokenizer) to an associated bias value from -100 to 100. You can use this [tokenizer tool](/tokenizer?view=bpe) (which works for both GPT-2 and GPT-3) to convert text to token IDs. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token.
    # 
    # As an example, you can pass `{"50256": -100}` to prevent the <|endoftext|> token from being generated
    @jsondata:Name {value: "logit_bias"}
    record {}? logitBias?;
    # The maximum number of [tokens](/tokenizer) to generate in the completion.
    # 
    # The token count of your prompt plus `max_tokens` cannot exceed the model's context length. [Example Python code](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb) for counting tokens
    @jsondata:Name {value: "max_tokens"}
    int? maxTokens = 16;
    # Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.
    # 
    # [See more information about frequency and presence penalties.](/docs/api-reference/parameter-details)
    @jsondata:Name {value: "presence_penalty"}
    decimal? presencePenalty = 0;
    # Echo back the prompt in addition to the completion
    boolean? echo = false;
    # The suffix that comes after a completion of inserted text
    string? suffix?;
    # How many completions to generate for each prompt.
    # 
    # **Note:** Because this parameter generates many completions, it can quickly consume your token quota. Use carefully and ensure that you have reasonable settings for `max_tokens` and `stop`
    int? n = 1;
    # Include the log probabilities on the `logprobs` most likely tokens, as well the chosen tokens. For example, if `logprobs` is 5, the API will return a list of the 5 most likely tokens. The API will always return the `logprob` of the sampled token, so there may be up to `logprobs+1` elements in the response.
    # 
    # The maximum value for `logprobs` is 5
    int? logprobs?;
    # An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.
    # 
    # We generally recommend altering this or `temperature` but not both
    @jsondata:Name {value: "top_p"}
    decimal? topP = 1;
    # Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim.
    # 
    # [See more information about frequency and presence penalties.](/docs/api-reference/parameter-details)
    @jsondata:Name {value: "frequency_penalty"}
    decimal? frequencyPenalty = 0;
    # Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence
    string|string[]?? stop = ();
    # Generates `best_of` completions server-side and returns the "best" (the one with the highest log probability per token). Results cannot be streamed.
    # 
    # When used with `n`, `best_of` controls the number of candidate completions and `n` specifies how many to return – `best_of` must be greater than `n`.
    # 
    # **Note:** Because this parameter generates many completions, it can quickly consume your token quota. Use carefully and ensure that you have reasonable settings for `max_tokens` and `stop`
    @jsondata:Name {value: "best_of"}
    int? bestOf = 1;
    # Whether to stream back partial progress. If set, tokens will be sent as data-only [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format) as they become available, with the stream terminated by a `data: [DONE]` message. [Example Python code](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_stream_completions.ipynb)
    boolean? 'stream = false;
    # What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.
    # 
    # We generally recommend altering this or `top_p` but not both
    decimal? temperature = 1;
    # ID of the model to use. You can use the [List models](/docs/api-reference/models/list) API to see all of your available models, or see our [Model overview](/docs/models/overview) for descriptions of them
    string|"text-davinci-003"|"text-davinci-002"|"text-davinci-001"|"code-davinci-002"|"text-curie-001"|"text-babbage-001"|"text-ada-001" model;
    # The prompt(s) to generate completions for, encoded as a string, array of strings, array of tokens, or array of token arrays.
    # 
    # Note that <|endoftext|> is the document separator that the model sees during training, so if a prompt is not specified the model will generate as if from the beginning of a new document
    string|string[]|int[]|PromptItemsArray[]? prompt = "<|endoftext|>";
    # A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids)
    string user?;
};

public type CreateChatCompletionResponse record {
    int created;
    CreateCompletionResponseUsage usage?;
    string model;
    string id;
    CreateChatCompletionResponseChoices[] choices;
    string 'object;
};

public type CreateEmbeddingResponseData record {
    int index;
    decimal[] embedding;
    string 'object;
};

public type CreateFileRequest record {|
    # Name of the [JSON Lines](https://jsonlines.readthedocs.io/en/latest/) file to be uploaded.
    # 
    # If the `purpose` is set to "fine-tune", each line is a JSON record with "prompt" and "completion" fields representing your [training examples](/docs/guides/fine-tuning/prepare-training-data)
    record {byte[] fileContent; string fileName;} file;
    # The intended purpose of the uploaded documents.
    # 
    # Use "fine-tune" for [Fine-tuning](/docs/api-reference/fine-tunes). This allows us to validate the format of the uploaded file
    string purpose;
|};

public type CreateCompletionResponse record {
    int created;
    CreateCompletionResponseUsage usage?;
    string model;
    string id;
    CreateCompletionResponseChoices[] choices;
    string 'object;
};

public type PromptItemsArray int[];

public type CreateImageVariationRequest record {
    # The image to use as the basis for the variation(s). Must be a valid PNG file, less than 4MB, and square
    record {byte[] fileContent; string fileName;} image;
    # The format in which the generated images are returned. Must be one of `url` or `b64_json`
    @jsondata:Name {value: "response_format"}
    "url"|"b64_json"? responseFormat = "url";
    # The size of the generated images. Must be one of `256x256`, `512x512`, or `1024x1024`
    "256x256"|"512x512"|"1024x1024"? size = "1024x1024";
    # A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids)
    string user?;
    # The number of images to generate. Must be between 1 and 10
    int? n = 1;
};

public type ChatCompletionResponseMessage record {
    # The role of the author of this message
    "system"|"user"|"assistant"|"function" role;
    @jsondata:Name {value: "function_call"}
    ChatCompletionRequestMessageFunctionCall functionCall?;
    # The contents of the message
    string? content?;
};

public type CreateImageEditRequest record {
    # The image to edit. Must be a valid PNG file, less than 4MB, and square. If mask is not provided, image must have transparency, which will be used as the mask
    record {byte[] fileContent; string fileName;} image;
    # The format in which the generated images are returned. Must be one of `url` or `b64_json`
    @jsondata:Name {value: "response_format"}
    "url"|"b64_json"? responseFormat = "url";
    # The size of the generated images. Must be one of `256x256`, `512x512`, or `1024x1024`
    "256x256"|"512x512"|"1024x1024"? size = "1024x1024";
    # A text description of the desired image(s). The maximum length is 1000 characters
    string prompt;
    # A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids)
    string user?;
    # The number of images to generate. Must be between 1 and 10
    int? n = 1;
    # An additional image whose fully transparent areas (e.g. where alpha is zero) indicate where `image` should be edited. Must be a valid PNG file, less than 4MB, and have the same dimensions as `image`
    record {byte[] fileContent; string fileName;} mask?;
};

public type ListModelsResponse record {
    Model[] data;
    string 'object;
};

public type CreateFineTuneRequest record {
    # The ID of an uploaded file that contains training data.
    # 
    # See [upload file](/docs/api-reference/files/upload) for how to upload a file.
    # 
    # Your dataset must be formatted as a JSONL file, where each training
    # example is a JSON object with the keys "prompt" and "completion".
    # Additionally, you must upload your file with the purpose `fine-tune`.
    # 
    # See the [fine-tuning guide](/docs/guides/fine-tuning/creating-training-data) for more details
    @jsondata:Name {value: "training_file"}
    string trainingFile;
    # The number of epochs to train the model for. An epoch refers to one
    # full cycle through the training dataset
    @jsondata:Name {value: "n_epochs"}
    int? nEpochs = 4;
    # The batch size to use for training. The batch size is the number of
    # training examples used to train a single forward and backward pass.
    # 
    # By default, the batch size will be dynamically configured to be
    # ~0.2% of the number of examples in the training set, capped at 256 -
    # in general, we've found that larger batch sizes tend to work better
    # for larger datasets
    @jsondata:Name {value: "batch_size"}
    int? batchSize?;
    # The number of classes in a classification task.
    # 
    # This parameter is required for multiclass classification
    @jsondata:Name {value: "classification_n_classes"}
    int? classificationNClasses?;
    # The ID of an uploaded file that contains validation data.
    # 
    # If you provide this file, the data is used to generate validation
    # metrics periodically during fine-tuning. These metrics can be viewed in
    # the [fine-tuning results file](/docs/guides/fine-tuning/analyzing-your-fine-tuned-model).
    # Your train and validation data should be mutually exclusive.
    # 
    # Your dataset must be formatted as a JSONL file, where each validation
    # example is a JSON object with the keys "prompt" and "completion".
    # Additionally, you must upload your file with the purpose `fine-tune`.
    # 
    # See the [fine-tuning guide](/docs/guides/fine-tuning/creating-training-data) for more details
    @jsondata:Name {value: "validation_file"}
    string? validationFile?;
    # If this is provided, we calculate F-beta scores at the specified
    # beta values. The F-beta score is a generalization of F-1 score.
    # This is only used for binary classification.
    # 
    # With a beta of 1 (i.e. the F-1 score), precision and recall are
    # given the same weight. A larger beta score puts more weight on
    # recall and less on precision. A smaller beta score puts more weight
    # on precision and less on recall
    @jsondata:Name {value: "classification_betas"}
    decimal[]? classificationBetas?;
    # The weight to use for loss on the prompt tokens. This controls how
    # much the model tries to learn to generate the prompt (as compared
    # to the completion which always has a weight of 1.0), and can add
    # a stabilizing effect to training when completions are short.
    # 
    # If prompts are extremely long (relative to completions), it may make
    # sense to reduce this weight so as to avoid over-prioritizing
    # learning the prompt
    @jsondata:Name {value: "prompt_loss_weight"}
    decimal? promptLossWeight = 0.01;
    # The name of the base model to fine-tune. You can select one of "ada",
    # "babbage", "curie", "davinci", or a fine-tuned model created after 2022-04-21.
    # To learn more about these models, see the
    # [Models](https://platform.openai.com/docs/models) documentation
    string|"ada"|"babbage"|"curie"|"davinci"? model = "curie";
    # If set, we calculate classification-specific metrics such as accuracy
    # and F-1 score using the validation set at the end of every epoch.
    # These metrics can be viewed in the [results file](/docs/guides/fine-tuning/analyzing-your-fine-tuned-model).
    # 
    # In order to compute classification metrics, you must provide a
    # `validation_file`. Additionally, you must
    # specify `classification_n_classes` for multiclass classification or
    # `classification_positive_class` for binary classification
    @jsondata:Name {value: "compute_classification_metrics"}
    boolean? computeClassificationMetrics = false;
    # The positive class in binary classification.
    # 
    # This parameter is needed to generate precision, recall, and F1
    # metrics when doing binary classification
    @jsondata:Name {value: "classification_positive_class"}
    string? classificationPositiveClass?;
    # A string of up to 40 characters that will be added to your fine-tuned model name.
    # 
    # For example, a `suffix` of "custom-model-name" would produce a model name like `ada:ft-your-org:custom-model-name-2022-02-15-04-21-04`
    string? suffix?;
    # The learning rate multiplier to use for training.
    # The fine-tuning learning rate is the original learning rate used for
    # pretraining multiplied by this value.
    # 
    # By default, the learning rate multiplier is the 0.05, 0.1, or 0.2
    # depending on final `batch_size` (larger learning rates tend to
    # perform better with larger batch sizes). We recommend experimenting
    # with values in the range 0.02 to 0.2 to see what produces the best
    # results
    @jsondata:Name {value: "learning_rate_multiplier"}
    decimal? learningRateMultiplier?;
};

public type Model record {
    string id;
    string 'object;
    int created;
    string owned_by;
};

public type ListFilesResponse record {
    OpenAIFile[] data;
    string 'object;
};

# The parameters the functions accepts, described as a JSON Schema object. See the [guide](/docs/guides/gpt/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format
public type ChatCompletionFunctionParameters record {
};

public type CreateModerationResponseOk record {|
    *http:Ok;
    CreateModerationResponse body;
|};
